version: '3.9'

services:

  prometheus:
    image: prom/prometheus:v2.49.1
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - metrics_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090"
    restart: always
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-enterprise:10.0.10
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    networks:
      - monitoring
    volumes:
     - 'grafana_data:/var/lib/grafana'

volumes:
  metrics_data:
  grafana_data:

networks:
  monitoring:
