version: '3.9'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.19.4-alpine
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    restart: 'always'
    ports:
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring

volumes:
  portainer_data:
  websrv-data:

networks:
  monitoring:
