# use this docker compose config file if you want to install node exporter using docker compose.
version: '3.8'

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.7.0
    container_name: node_exporter
    restart: always
    ports:
      - 9100:9100
    volumes:
      - '/:/host:ro,rslave'
